using BusinessLogic.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessLogic.DataProvider.PresentationManager
{
    public class PresentationManagerMock : IPresentationManager
    {
        public List<Domain.Presentation> GetAllPresentation()
        {
            List<Speaker> speakers = new List<Speaker>();
            speakers.Add(new Speaker
            {
                ID = 0, 
                Country = "Germany",
                FirstName = "Marc",
                LastName = "Meier",
                Gender = "Male",
                Title = "Dr."
            }); 
     
            List<Presentation> presentations = new List<Presentation>();
            presentations.Add(new Presentation { ID = 0, Title = "Evolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 1, Title = "Evolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 2, Title = "Evolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 3, Title = "Evolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(3), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 4, Title = "Evolution of the implementation in .NET 11.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(4), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });
            presentations.Add(new Presentation { ID = 5, Title = "Evolution of the implementation in .NET 12.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(5), EndDateTime = DateTime.Now.AddDays(5).AddHours(2) });
            presentations.Add(new Presentation { ID = 6, Title = "Evolution of the implementation in .NET 13.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(7), EndDateTime = DateTime.Now.AddDays(7).AddHours(2) });
            presentations.Add(new Presentation { ID = 7, Title = "Evolution of the implementation in .NET 14.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 8, Title = "Evolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });

            presentations.Add(new Presentation { ID = 9, Title = "Avolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 10, Title = "Bvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 11, Title = "Cvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 12, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 13, Title = "Evolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 14, Title = "Fvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });

            presentations.Add(new Presentation { ID = 20, Title = "Avolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 21, Title = "Bvolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 22, Title = "Xvolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 23, Title = "Dvolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(3), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 24, Title = "Fvolution of the implementation in .NET 11.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(4), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });
            presentations.Add(new Presentation { ID = 25, Title = "Gvolution of the implementation in .NET 12.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(5), EndDateTime = DateTime.Now.AddDays(5).AddHours(2) });
            presentations.Add(new Presentation { ID = 26, Title = "Evolution of the implementation in .NET 13.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(7), EndDateTime = DateTime.Now.AddDays(7).AddHours(2) });
            presentations.Add(new Presentation { ID = 27, Title = "Rvolution of the implementation in .NET 14.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 28, Title = "Tvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });

            presentations.Add(new Presentation { ID = 29, Title = "Fvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 30, Title = "Gvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 31, Title = "Fvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 32, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 33, Title = "Uvolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 34, Title = "Uvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });
    

            return presentations; 
        }



        public List<Presentation> GetPresentationBySpeaker(Speaker speaker)
        {
            List<Speaker> speakers1 = new List<Speaker>();
            speakers1.Add(new Speaker
            {
                ID = 0,
                Country = "Germany 1",
                FirstName = "Marc 1",
                LastName = "Meier 1",
                Gender = "Male 1",
                Title = "Dr. 1"
            });

            List<Speaker> speakers2 = new List<Speaker>();
            speakers2.Add(new Speaker
            {
                ID = 1,
                Country = "Germany 2",
                FirstName = "Marc 2",
                LastName = "Meier 2",
                Gender = "Male 2",
                Title = "Dr. 2"
            });

            List<Speaker> speakers3 = new List<Speaker>();
            speakers3.Add(new Speaker
            {
                ID = 3,
                Country = "Germany 3",
                FirstName = "Marc 3",
                LastName = "Meier 3",
                Gender = "Male 3",
                Title = "Dr. 3"
            }); 
            List<Presentation> presentations = new List<Presentation>();
            presentations.Add(new Presentation { ID = 0, Title = "Evolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 1, Title = "Evolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 2, Title = "Evolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 3, Title = "Evolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 4, Title = "Evolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            
            presentations.Add(new Presentation { ID = 5, Title = "Evolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 6, Title = "Evolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 7, Title = "Evolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });

            presentations.Add(new Presentation { ID = 9, Title = "Avolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 10, Title = "Bvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 11, Title = "Cvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 12, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 13, Title = "Evolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 14, Title = "Fvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });

            presentations.Add(new Presentation { ID = 20, Title = "Avolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 21, Title = "Bvolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 22, Title = "Xvolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 23, Title = "Dvolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(3), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 24, Title = "Fvolution of the implementation in .NET 11.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(4), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });
            presentations.Add(new Presentation { ID = 25, Title = "Gvolution of the implementation in .NET 12.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(5), EndDateTime = DateTime.Now.AddDays(5).AddHours(2) });
            presentations.Add(new Presentation { ID = 26, Title = "Evolution of the implementation in .NET 13.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(7), EndDateTime = DateTime.Now.AddDays(7).AddHours(2) });
            presentations.Add(new Presentation { ID = 27, Title = "Rvolution of the implementation in .NET 14.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2) });
            presentations.Add(new Presentation { ID = 28, Title = "Tvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });

            presentations.Add(new Presentation { ID = 29, Title = "Fvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 30, Title = "Gvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 31, Title = "Fvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2) });
            presentations.Add(new Presentation { ID = 32, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 33, Title = "Uvolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2) });
            presentations.Add(new Presentation { ID = 34, Title = "Uvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2) });
  
            
            return presentations;      
        
        }


        public Presentation GetPresentationByID(Presentation presentation)
        {
            List<Speaker> speakers1 = new List<Speaker>();
            speakers1.Add(new Speaker
            {
                ID = 0,
                Country = "Germany 1",
                FirstName = "Marc 1",
                LastName = "Meier 1",
                Gender = "Male 1",
                Title = "Dr. 1"
            });

            List<Speaker> speakers2 = new List<Speaker>();
            speakers2.Add(new Speaker
            {
                ID = 1,
                Country = "Germany 2",
                FirstName = "Marc 2",
                LastName = "Meier 2",
                Gender = "Male 2",
                Title = "Dr. 2"
            });

            List<Speaker> speakers3 = new List<Speaker>();
            speakers3.Add(new Speaker
            {
                ID = 3,
                Country = "Germany 3",
                FirstName = "Marc 3",
                LastName = "Meier 3",
                Gender = "Male 3",
                Title = "Dr. 3"
            });
            List<Presentation> presentations = new List<Presentation>();
            presentations.Add(new Presentation { ID = 0, Title = "Evolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 1, Title = "Evolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 2, Title = "Evolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 3, Title = "Evolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 4, Title = "Evolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });

            presentations.Add(new Presentation { ID = 5, Title = "Evolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 6, Title = "Evolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 7, Title = "Evolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });

            presentations.Add(new Presentation { ID = 9, Title = "Avolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 10, Title = "Bvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 11, Title = "Cvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 12, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 13, Title = "Evolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 14, Title = "Fvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers3, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });

            presentations.Add(new Presentation { ID = 20, Title = "Avolution of the implementation in .NET 7.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now, EndDateTime = DateTime.Now.AddDays(2) });
            presentations.Add(new Presentation { ID = 21, Title = "Bvolution of the implementation in .NET 8.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2), Abstract = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc," });
            presentations.Add(new Presentation { ID = 22, Title = "Xvolution of the implementation in .NET 9.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "This is the abstract of the presentation,dsfsdf 8" });
            presentations.Add(new Presentation { ID = 23, Title = "Dvolution of the implementation in .NET 10.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(3), EndDateTime = DateTime.Now.AddDays(3).AddHours(2), Abstract = "This is the abstract of the presentation,gsdfg 8" });
            presentations.Add(new Presentation { ID = 24, Title = "Fvolution of the implementation in .NET 11.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(4), EndDateTime = DateTime.Now.AddDays(4).AddHours(2), Abstract = "This is the abstract of the presentation,sdfgsdfg 8" });
            presentations.Add(new Presentation { ID = 25, Title = "Gvolution of the implementation in .NET 12.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(5), EndDateTime = DateTime.Now.AddDays(5).AddHours(2), Abstract = "This is the abstract of the presentation,sfgsdfg 8" });
            presentations.Add(new Presentation { ID = 26, Title = "Evolution of the implementation in .NET 13.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(7), EndDateTime = DateTime.Now.AddDays(7).AddHours(2), Abstract = "This is the abstract of the presentation,sdfg 8" });
            presentations.Add(new Presentation { ID = 27, Title = "Rvolution of the implementation in .NET 14.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(1).AddHours(2), Abstract = "This is the abstract of the presentation,sgsdfgs 8" });
            presentations.Add(new Presentation { ID = 28, Title = "Tvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers2, StartDateTime = DateTime.Now.AddDays(2), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "This is the abstract of the presentation,sfgsdfg 8" });

            presentations.Add(new Presentation { ID = 29, Title = "Fvolution of the implementation in .NET 15.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "This is the abstract of the presentation,4q5213452345 8" });
            presentations.Add(new Presentation { ID = 30, Title = "Gvolution of the implementation in .NET 16.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "This is the abstract of the presentation,23453245 8" });
            presentations.Add(new Presentation { ID = 31, Title = "Fvolution of the implementation in .NET 17.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(2).AddHours(2), Abstract = "This is the abstract of the presentation,345234 8" });
            presentations.Add(new Presentation { ID = 32, Title = "Dvolution of the implementation in .NET 18.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2), Abstract = "This is the abstract of the presentation,523452345 8" });
            presentations.Add(new Presentation { ID = 33, Title = "Uvolution of the implementation in .NET 19.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(3).AddHours(2), Abstract = "This is the abstract of the presentation, 234523458" });
            presentations.Add(new Presentation { ID = 34, Title = "Uvolution of the implementation in .NET 20.0", Type = "Round Table", Speaker = speakers1, StartDateTime = DateTime.Now.AddDays(1), EndDateTime = DateTime.Now.AddDays(4).AddHours(2), Abstract = "This is the abstract of the presentation, 32458" });
  

            return presentations.Find(presentationTemp=>presentationTemp.ID == presentation.ID);     
        }
    }
}
